global.nSkills = 0;
global.SKILL[global.nSkills, 0] = "Sol"; //ai
global.SKILL[global.nSkills, 1] = "Recover HP equal to half the damage dealt to the enemy.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 6; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 50; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 1;
global.SKILL[global.nSkills, 0] = "Astra"; //ai
global.SKILL[global.nSkills, 1] = "Deals 5 consecutive hits at half damage.";
global.SKILL[global.nSkills, 2] = 1; //index
global.SKILL[global.nSkills, 3] = 10; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 5; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 2;
global.SKILL[global.nSkills, 0] = "Vantage";
global.SKILL[global.nSkills, 1] = "Strike first during an enemy attack when HP is under half.";
global.SKILL[global.nSkills, 2] = 2; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 4; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 50; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 3;
global.SKILL[global.nSkills, 0] = "Rally Movement";
global.SKILL[global.nSkills, 1] = "Movement +1 to all allies within a 3 tile radius for one turn.";
global.SKILL[global.nSkills, 2] = 3; //index
global.SKILL[global.nSkills, 3] = 8; //SP cost
global.SKILL[global.nSkills, 4] = 1; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 3; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = sfx_rallyMovement; //sound

global.nSkills = 4;
global.SKILL[global.nSkills, 0] = "Rally Strength";
global.SKILL[global.nSkills, 1] = "Strength +5 to all allies within a 3 tile radius for one turn.";
global.SKILL[global.nSkills, 2] = 4; //index
global.SKILL[global.nSkills, 3] = 10; //SP cost
global.SKILL[global.nSkills, 4] = 1; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 3; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 5; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = sfx_charge; //sound

global.nSkills = 5;
global.SKILL[global.nSkills, 0] = "Luna"; //ai
global.SKILL[global.nSkills, 1] = "Remove half of the enemy defenses when engaging.";
global.SKILL[global.nSkills, 2] = 5; //index
global.SKILL[global.nSkills, 3] = 8; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 2; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0.5; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 6;
global.SKILL[global.nSkills, 0] = "Flourish"; //ai1
global.SKILL[global.nSkills, 1] = "Unit gains +25 crit if they haven't moved.";
global.SKILL[global.nSkills, 2] = 6; //index
global.SKILL[global.nSkills, 3] = 4; //SP cost
global.SKILL[global.nSkills, 4] = 2; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 25; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 7;
global.SKILL[global.nSkills, 0] = "Snipe";
global.SKILL[global.nSkills, 1] = "Unit gains +35 hit if they haven't moved.";
global.SKILL[global.nSkills, 2] = 7; //index
global.SKILL[global.nSkills, 3] = 4; //SP cost
global.SKILL[global.nSkills, 4] = 2; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 35; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 8;
global.SKILL[global.nSkills, 0] = "Lovestruck";
global.SKILL[global.nSkills, 1] = "Female ally units within a 2 tile radius of this unit give them +1 ATK, +1 DEF and -3 AVO.";
global.SKILL[global.nSkills, 2] = 8; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 4; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = 1; //subtype2
global.SKILL[global.nSkills, 7] = 4; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 2; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 1; //might2
global.SKILL[global.nSkills, 14] = -3; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 9;
global.SKILL[global.nSkills, 0] = "Sandy Love";
global.SKILL[global.nSkills, 1] = "Luck +30 to all allies within a 3 tile radius for two turns.";
global.SKILL[global.nSkills, 2] = 12; //index
global.SKILL[global.nSkills, 3] = 8; //SP cost
global.SKILL[global.nSkills, 4] = 1; //type
global.SKILL[global.nSkills, 5] = 2; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 3; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 30; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = sfx_sandiness; //sound

global.nSkills = 10;
global.SKILL[global.nSkills, 0] = "Sandiness";
global.SKILL[global.nSkills, 1] = "Ally units within a 3 tile radius of Sandy have all their skill SP costs reduced by 2 points.";
global.SKILL[global.nSkills, 2] = 9; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 3; //type
global.SKILL[global.nSkills, 5] = 5; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 3; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 2; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 11;
global.SKILL[global.nSkills, 0] = "Discipline";
global.SKILL[global.nSkills, 1] = "Weapon Experience x2.";
global.SKILL[global.nSkills, 2] = 19; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 10; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 2; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 12;
global.SKILL[global.nSkills, 0] = "Pass";
global.SKILL[global.nSkills, 1] = "User can move through tiles occupied by an enemy unit.";
global.SKILL[global.nSkills, 2] = 20; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 50; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 13;
global.SKILL[global.nSkills, 0] = "Wrath";
global.SKILL[global.nSkills, 1] = "Critical +20 when under half HP.";
global.SKILL[global.nSkills, 2] = 21; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 14; //type
global.SKILL[global.nSkills, 5] = -1; //subtype1
global.SKILL[global.nSkills, 6] = 3; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 50; //might1
global.SKILL[global.nSkills, 13] = 20; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 14;
global.SKILL[global.nSkills, 0] = "Gamble";
global.SKILL[global.nSkills, 1] = "Hit rate -5, Critical +10.";
global.SKILL[global.nSkills, 2] = 22; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 30; //type
global.SKILL[global.nSkills, 5] = 2; //subtype1
global.SKILL[global.nSkills, 6] = 3; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -5; //might1
global.SKILL[global.nSkills, 13] = 10; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 15;
global.SKILL[global.nSkills, 0] = "Milkshake";
global.SKILL[global.nSkills, 1] = "Male ally units within a 2 tile radius of this unit grant +1 ATK and -1 DEF.";
global.SKILL[global.nSkills, 2] = 8; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 5; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = 1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 2; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = -1; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 16;
global.SKILL[global.nSkills, 0] = "Paragon";
global.SKILL[global.nSkills, 1] = "User receives double EXP in battles.";
global.SKILL[global.nSkills, 2] = 10; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 10; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 2; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 17;
global.SKILL[global.nSkills, 0] = "Cripple";
global.SKILL[global.nSkills, 1] = "Enemy's Mag -2, Def/Res -3; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 2; //subtype1
global.SKILL[global.nSkills, 6] = 6; //subtype2
global.SKILL[global.nSkills, 7] = 7; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -2; //might1
global.SKILL[global.nSkills, 13] = -3; //might2
global.SKILL[global.nSkills, 14] = -3; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 18;
global.SKILL[global.nSkills, 0] = "Elemental";
global.SKILL[global.nSkills, 1] = "Magic users within a 2 tile radius of this unit grant +2 ATK, SKILL, DEF.";
global.SKILL[global.nSkills, 2] = 13; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 6; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = 1; //subtype2
global.SKILL[global.nSkills, 7] = 9; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 2; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 2; //might1
global.SKILL[global.nSkills, 13] = 2; //might2
global.SKILL[global.nSkills, 14] = 2; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 19;
global.SKILL[global.nSkills, 0] = "Red Starved";
global.SKILL[global.nSkills, 1] = "User heals 4 HP and gains +4 Str (reduced by 1 each turn) upon defeating an enemy unit while under 50% HP.";
global.SKILL[global.nSkills, 2] = 14; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 12; //type
global.SKILL[global.nSkills, 5] = 10; //subtype1
global.SKILL[global.nSkills, 6] = 0; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = 0; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 4; //might1
global.SKILL[global.nSkills, 13] = 4; //might2
global.SKILL[global.nSkills, 14] = -1; //might3
global.SKILL[global.nSkills, 15] = 50; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 20;
global.SKILL[global.nSkills, 0] = "Lunge";
global.SKILL[global.nSkills, 1] = "When this unit engages in combat, switches positions with the target.";
global.SKILL[global.nSkills, 2] = 15; //index
global.SKILL[global.nSkills, 3] = 5; //SP cost
global.SKILL[global.nSkills, 4] = 13; //type
global.SKILL[global.nSkills, 5] = -1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 21;
global.SKILL[global.nSkills, 0] = "High Noon";
global.SKILL[global.nSkills, 1] = "Deals 3 consecutive hits at half damage, ignoring all armor and resistance.";
global.SKILL[global.nSkills, 2] = 16; //index
global.SKILL[global.nSkills, 3] = 14; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = 2; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 3; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 22;
global.SKILL[global.nSkills, 0] = "Allure";
global.SKILL[global.nSkills, 1] = "Convert the target for one turn (cannot convert boss enemies).";
global.SKILL[global.nSkills, 2] = 17; //index
global.SKILL[global.nSkills, 3] = 10; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 20; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 23;
global.SKILL[global.nSkills, 0] = "Buzzer Beater";
global.SKILL[global.nSkills, 1] = "When user initiates combat under 20% HP, gain 50% HIT and CRIT. If the target is defeated, user can move again.";
global.SKILL[global.nSkills, 2] = 18; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 14; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = 2; //subtype2
global.SKILL[global.nSkills, 7] = 3; //subtype3
global.SKILL[global.nSkills, 8] = 0; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 20; //might1
global.SKILL[global.nSkills, 13] = 50; //might2
global.SKILL[global.nSkills, 14] = 50; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 24;
global.SKILL[global.nSkills, 0] = "Rain-Blow";
global.SKILL[global.nSkills, 1] = "Gain 1 ATK/1 DEF for each 30% of missing health when initiating combat.";
global.SKILL[global.nSkills, 2] = 13; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 15; //type
global.SKILL[global.nSkills, 5] = 100; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 30; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 25;
global.SKILL[global.nSkills, 0] = "Capture";
global.SKILL[global.nSkills, 1] = "When defeating an enemy in combat, capture them and send them to Sandy Jail.";
global.SKILL[global.nSkills, 2] = 11; //index
global.SKILL[global.nSkills, 3] = 10; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 21; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 26;
global.SKILL[global.nSkills, 0] = "Lightning";
global.SKILL[global.nSkills, 1] = "Deal bonus magic damage on hit based on MAG.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 23; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 27;
global.SKILL[global.nSkills, 0] = "Recovery";
global.SKILL[global.nSkills, 1] = "Recover HP on hit.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 22; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 28;
global.SKILL[global.nSkills, 0] = "Exhaust";
global.SKILL[global.nSkills, 1] = "Enemy's Str/Mag -4; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 1; //subtype1
global.SKILL[global.nSkills, 6] = 2; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -4; //might1
global.SKILL[global.nSkills, 13] = -4; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 29;
global.SKILL[global.nSkills, 0] = "Shatter";
global.SKILL[global.nSkills, 1] = "Enemy's Def/Res -4; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 6; //subtype1
global.SKILL[global.nSkills, 6] = 7; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -4; //might1
global.SKILL[global.nSkills, 13] = -4; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 30;
global.SKILL[global.nSkills, 0] = "Soothe";
global.SKILL[global.nSkills, 1] = "Enemy's Spd -6; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 4; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -6; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 31;
global.SKILL[global.nSkills, 0] = "Daze";
global.SKILL[global.nSkills, 1] = "Enemy's Lck/Skill -6; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 3; //subtype1
global.SKILL[global.nSkills, 6] = 5; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -6; //might1
global.SKILL[global.nSkills, 13] = -6; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound


global.nSkills = 32;
global.SKILL[global.nSkills, 0] = "Freeze";
global.SKILL[global.nSkills, 1] = "Enemy's Mag/Spd -5; recover by 1 each turn.";
global.SKILL[global.nSkills, 2] = 0; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 11; //type
global.SKILL[global.nSkills, 5] = 4; //subtype1
global.SKILL[global.nSkills, 6] = 2; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = -5; //might1
global.SKILL[global.nSkills, 13] = -5; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 33;
global.SKILL[global.nSkills, 0] = "Shove"; //ai
global.SKILL[global.nSkills, 1] = "Move target 1 space away from unit";
global.SKILL[global.nSkills, 2] = 23; //index
global.SKILL[global.nSkills, 3] = 3; //SP cost
global.SKILL[global.nSkills, 4] = 60; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 34;
global.SKILL[global.nSkills, 0] = "Rescue"; //ai
global.SKILL[global.nSkills, 1] = "Pick up target infantry, suffer a -2 speed debuff until target is put back down.";
global.SKILL[global.nSkills, 2] = 24; //index
global.SKILL[global.nSkills, 3] = 3; //SP cost
global.SKILL[global.nSkills, 4] = 61; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 35;
global.SKILL[global.nSkills, 0] = "Drop"; //ai
global.SKILL[global.nSkills, 1] = "Put back down your target.";
global.SKILL[global.nSkills, 2] = 25; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 62; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 36;
global.SKILL[global.nSkills, 0] = "Dash"; //ai
global.SKILL[global.nSkills, 1] = "Allows user to move an additional 2 spaces, but will not be able to attack.";
global.SKILL[global.nSkills, 2] = 26; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 63; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 2; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = sfx_rallyMovement; //sound

global.nSkills = 37;
global.SKILL[global.nSkills, 0] = "Thief Kit"; //ai
global.SKILL[global.nSkills, 1] = "Allows the user to open doors and chests and grants the ability to steal from an enemy.";
global.SKILL[global.nSkills, 2] = 27; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 70; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 38;
global.SKILL[global.nSkills, 0] = "Augment"; //ai
global.SKILL[global.nSkills, 1] = "Temporarily boost a dark tome at the cost of 3 HP.";
global.SKILL[global.nSkills, 2] = 28; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 71; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 3; //might1
global.SKILL[global.nSkills, 13] = 16; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 39;
global.SKILL[global.nSkills, 0] = "Mirror";
global.SKILL[global.nSkills, 1] = "When this unit is engaged, changes positions.";
global.SKILL[global.nSkills, 2] = 35; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 72; //type
global.SKILL[global.nSkills, 5] = -1; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 40;
global.SKILL[global.nSkills, 0] = "Annihilation"; //ai
global.SKILL[global.nSkills, 1] = "Remove all enemy defenses when engaging.";
global.SKILL[global.nSkills, 2] = 5; //index
global.SKILL[global.nSkills, 3] = 35; //SP cost
global.SKILL[global.nSkills, 4] = 0; //type
global.SKILL[global.nSkills, 5] = 2; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 41;
global.SKILL[global.nSkills, 0] = "Rage";
global.SKILL[global.nSkills, 1] = "Attack +20 when the user has 20% HP or less.";
global.SKILL[global.nSkills, 2] = 21; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 14; //type
global.SKILL[global.nSkills, 5] = -1; //subtype1
global.SKILL[global.nSkills, 6] = 0; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 20; //might1
global.SKILL[global.nSkills, 13] = 20; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 42;
global.SKILL[global.nSkills, 0] = "Galeforce";
global.SKILL[global.nSkills, 1] = "Allows the user another full action after they defeat an enemy during the user's Turn (only once per Turn).";
global.SKILL[global.nSkills, 2] = 36; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 16; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = 0; //subtype2
global.SKILL[global.nSkills, 7] = 0; //subtype3
global.SKILL[global.nSkills, 8] = 0; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 0; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

//Personal Skills (100-150)
global.nSkills = 100;
global.SKILL[global.nSkills, 0] = "Rogue's Charisma";
global.SKILL[global.nSkills, 1] = "Ally units within a 2 tile radius have all their skill SP costs reduced by 1 point.";
global.SKILL[global.nSkills, 2] = 9; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 3; //type
global.SKILL[global.nSkills, 5] = 5; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = 1; //minrange
global.SKILL[global.nSkills, 10] = 2; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 1; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = 0; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 101;
global.SKILL[global.nSkills, 0] = "Hollow Hunter";
global.SKILL[global.nSkills, 1] = "Forest tiles cost 1 movement, +15 hit, +15 avoid, +10 crit while in a forest tile.";
global.SKILL[global.nSkills, 2] = 9; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 18; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 15; //might1
global.SKILL[global.nSkills, 13] = 15; //might2
global.SKILL[global.nSkills, 14] = 10; //might3
global.SKILL[global.nSkills, 15] = -1; //might4
global.SKILL[global.nSkills, 16] = -1; //sound

global.nSkills = 102;
global.SKILL[global.nSkills, 0] = "Impulse Rush";
global.SKILL[global.nSkills, 1] = "+3 attack if targeted enemy is at full HP.";
global.SKILL[global.nSkills, 2] = 20; //index
global.SKILL[global.nSkills, 3] = 0; //SP cost
global.SKILL[global.nSkills, 4] = 19; //type
global.SKILL[global.nSkills, 5] = 0; //subtype1
global.SKILL[global.nSkills, 6] = -1; //subtype2
global.SKILL[global.nSkills, 7] = -1; //subtype3
global.SKILL[global.nSkills, 8] = -1; //subtype4
global.SKILL[global.nSkills, 9] = -1; //minrange
global.SKILL[global.nSkills, 10] = -1; //maxrange
global.SKILL[global.nSkills, 11] = 0; //animationType
global.SKILL[global.nSkills, 12] = 3; //might1
global.SKILL[global.nSkills, 13] = 0; //might2
global.SKILL[global.nSkills, 14] = 0; //might3
global.SKILL[global.nSkills, 15] = -1; //might4
global.SKILL[global.nSkills, 16] = -1; //sound


